### ISSUE TITLE
hi , im trying to use you cslPay , however whenever i call the function the whole app crash. Is it possible to get  sample working project that use your cslPay88 ?

### ISSUE THREAD

**Issue by rimiazizi** [tjwoon/csIPay88#1]

**Comment by ShukriSaad** [comment]
Im using ionic and it crashed on device whereas it will run successfully on emulator with 'ionic run -lc android'. any takers?

**Comment by rimiazizi** [comment]
So far i managed to use this wonderfully.  Do email me and i can share my
implementation code.

**Comment by ShukriSaad** [comment]
would love to, sir! but I can't see where can I get your email from github. but mine is matkeriuk@gmail.com

**Comment by tjwoon** [comment]
Sorry, totally missed this issue.

The app probably crashed because the iPay88 SDK does not request for Android permissions automatically + requires the AppCompat library. Latest release v1.0.0 fixes these two problems.

**Comment by ManigandanRaamanathan** [comment]
@rimiazizi  can you please share me the implementation code of ipay88 in ionic. 
Thank you.
