### ISSUE TITLE
Signature not match Error

### ISSUE THREAD

**Issue by AqibYaqoob** [tjwoon/csIPay88#11]
We are getting Signature not Match error when we set paymentId : "" to empty and if we give the paymentId then we get Payment Not Allow Issue ? 

Kindly Help us as soon as possible Thanks

**Comment by AqibYaqoob** [comment]
Any Update ??

**Comment by tjwoon** [comment]
Hi. Please raise this to iPay88. It is most likely an issue / misconfiguration in your merchant account.
