### ISSUE TITLE
Possibility to implement onSaveInstanceState() ?

### ISSUE THREAD

**Issue by rcha103** [tjwoon/csIPay88#13]
Hi, I'm using your plugin to my Mendix platform application. I realized that on Android, the application state is not saved. This is an issue for me since I'd like to execute some logic when the application resumes which are related to the current activity (for example, session related logic). For now, I cannot properly handle any failure callbacks since the app does not know the session of the app, and the app will crash. Any chance that onSaveInstanceState() will be implemented to accommodate this?

**Comment by tjwoon** [comment]
You should be saving the state of your own activity. That should be nothing to do with this plugin.
