### ISSUE TITLE
Unsafe implementation of WebViewClient.onReceivedSslError handler.

### ISSUE THREAD

**Issue by HafizahYS** [tjwoon/csIPay88#3]
Hi TJ Woon,

Recently, my app has been rejected by Google Play Store because of SSL Error Handler issue. (Kindly refer attachment for clearer view). Only by removing your ipay88 plugin then the app is approved. I am most likely to use your plugin in my cordova app. Please help checking on this issue. Do let me know if you have come out with other better solution. You may also check the following link to refer as it is recommended by google play team on this issue https://support.google.com/faqs/answer/7071387 .  I'd really appreciate if you can solve this issue in the nearest future. Looking forward to hear from you. Thanks!
![2017-04-27 07 14 35](https://cloud.githubusercontent.com/assets/28097075/25480976/c588f7be-2b7d-11e7-8815-df9f1c428bb6.jpg)

**Comment by tjwoon** [comment]
Hi Hafizah. That's odd... I am using this plugin in an app which is frequently updated and have not seen this issue yet.

Please let me know:

1. The version the plugin you installed: 'cordova plugin'
2. The version of Cordova Android you have installed: 'cordova platform'

If you have anything older than v1.0.2 of this plugin, please uninstall and reinstall it using this command: 'cordova plugin add cordova-plugin-ipay88'. I recently changed the ID of the plugin and forgot to update the README...

**Comment by HafizahYS** [comment]
The plugin version I installed is 0.0.8 and the version of Cordova Android is 6.1.2..

Okay will try your suggestion to reinstall the plugin. Thank you.

**Comment by HafizahYS** [comment]
Hi TJ Woon,

My app has been approved after I reinstalled the plugin. Thanks for your help!

**Comment by tjwoon** [comment]
👍🏼
